CREATE TABLE users(
  ID SERIAL PRIMARY KEY,
  USERNAME VARCHAR(225) NOT NULL UNIQUE ,
  PASSWORD VARCHAR(225) NOT NULL
);

CREATE TABLE AUTH_USER(
  AUTH_USER_ID SERIAL PRIMARY KEY ,
  USERNAME VARCHAR(225) NOT NULL ,
  AUTH_GROUP VARCHAR(225) NOT NULL,
  CONSTRAINT USER_AUTH_FK FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME),
  UNIQUE (USERNAME, AUTH_GROUP)
);