/*
 * This file is generated by jOOQ.
 */
package com.demo.rest.ajax.restdemoajax.db;


import com.demo.rest.ajax.restdemoajax.db.tables.Address;
import com.demo.rest.ajax.restdemoajax.db.tables.Human;
import com.demo.rest.ajax.restdemoajax.db.tables.Products;
import com.demo.rest.ajax.restdemoajax.db.tables.Student;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.address</code>.
     */
    public static final Address ADDRESS = com.demo.rest.ajax.restdemoajax.db.tables.Address.ADDRESS;

    /**
     * The table <code>public.human</code>.
     */
    public static final Human HUMAN = com.demo.rest.ajax.restdemoajax.db.tables.Human.HUMAN;

    /**
     * The table <code>public.products</code>.
     */
    public static final Products PRODUCTS = com.demo.rest.ajax.restdemoajax.db.tables.Products.PRODUCTS;

    /**
     * The table <code>public.student</code>.
     */
    public static final Student STUDENT = com.demo.rest.ajax.restdemoajax.db.tables.Student.STUDENT;
}
