/*
 * This file is generated by jOOQ.
 */
package com.demo.restservice.restservicedemohateoas.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.category_category_pk_seq</code>
     */
    public static final Sequence<Integer> CATEGORY_CATEGORY_PK_SEQ = new SequenceImpl<Integer>("category_category_pk_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.product_product_id_seq</code>
     */
    public static final Sequence<Integer> PRODUCT_PRODUCT_ID_SEQ = new SequenceImpl<Integer>("product_product_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
