/*
 * This file is generated by jOOQ.
 */
package com.demo.restservice.restservicedemohateoas.db;


import com.demo.restservice.restservicedemohateoas.db.tables.Category;
import com.demo.restservice.restservicedemohateoas.db.tables.Product;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.category</code>.
     */
    public static final Category CATEGORY = com.demo.restservice.restservicedemohateoas.db.tables.Category.CATEGORY;

    /**
     * The table <code>public.product</code>.
     */
    public static final Product PRODUCT = com.demo.restservice.restservicedemohateoas.db.tables.Product.PRODUCT;
}
