/*
 * This file is generated by jOOQ.
 */
package com.demo.jooq.jooqdemo.db.routines;


import com.demo.jooq.jooqdemo.db.Public;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Salestax extends AbstractRoutine<BigDecimal> {

    private static final long serialVersionUID = -407570465;

    /**
     * The parameter <code>public.salestax.RETURN_VALUE</code>.
     */
    public static final Parameter<BigDecimal> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.NUMERIC, false, false);

    /**
     * The parameter <code>public.salestax.tax</code>.
     */
    public static final Parameter<BigDecimal> TAX = createParameter("tax", org.jooq.impl.SQLDataType.NUMERIC, false, false);

    /**
     * Create a new routine call instance
     */
    public Salestax() {
        super("salestax", Public.PUBLIC, org.jooq.impl.SQLDataType.NUMERIC);

        setReturnParameter(RETURN_VALUE);
        addInParameter(TAX);
    }

    /**
     * Set the <code>tax</code> parameter IN value to the routine
     */
    public void setTax(BigDecimal value) {
        setValue(TAX, value);
    }

    /**
     * Set the <code>tax</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setTax(Field<BigDecimal> field) {
        setField(TAX, field);
    }
}
