/*
 * This file is generated by jOOQ.
 */
package com.demo.jooq.jooqdemo.db;


import com.demo.jooq.jooqdemo.db.tables.Address;
import com.demo.jooq.jooqdemo.db.tables.Human;
import com.demo.jooq.jooqdemo.db.tables.Products;
import com.demo.jooq.jooqdemo.db.tables.Student;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ADDRESS_PKEY = Indexes0.ADDRESS_PKEY;
    public static final Index HUMAN_PKEY = Indexes0.HUMAN_PKEY;
    public static final Index PRODUCTS_PKEY = Indexes0.PRODUCTS_PKEY;
    public static final Index STUDENT_PKEY = Indexes0.STUDENT_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ADDRESS_PKEY = Internal.createIndex("address_pkey", Address.ADDRESS, new OrderField[] { Address.ADDRESS.AID }, true);
        public static Index HUMAN_PKEY = Internal.createIndex("human_pkey", Human.HUMAN, new OrderField[] { Human.HUMAN.ID }, true);
        public static Index PRODUCTS_PKEY = Internal.createIndex("products_pkey", Products.PRODUCTS, new OrderField[] { Products.PRODUCTS.ID }, true);
        public static Index STUDENT_PKEY = Internal.createIndex("student_pkey", Student.STUDENT, new OrderField[] { Student.STUDENT.ID }, true);
    }
}
