/*
 * This file is generated by jOOQ.
 */
package com.demo.jooq.jooqdemo.db;


import com.demo.jooq.jooqdemo.db.tables.Address;
import com.demo.jooq.jooqdemo.db.tables.Human;
import com.demo.jooq.jooqdemo.db.tables.Products;
import com.demo.jooq.jooqdemo.db.tables.Student;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -689840807;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.address</code>.
     */
    public final Address ADDRESS = com.demo.jooq.jooqdemo.db.tables.Address.ADDRESS;

    /**
     * The table <code>public.human</code>.
     */
    public final Human HUMAN = com.demo.jooq.jooqdemo.db.tables.Human.HUMAN;

    /**
     * The table <code>public.products</code>.
     */
    public final Products PRODUCTS = com.demo.jooq.jooqdemo.db.tables.Products.PRODUCTS;

    /**
     * The table <code>public.student</code>.
     */
    public final Student STUDENT = com.demo.jooq.jooqdemo.db.tables.Student.STUDENT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ADDRESS_AID_SEQ,
            Sequences.HUMAN_ID_SEQ,
            Sequences.STUDENT_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Address.ADDRESS,
            Human.HUMAN,
            Products.PRODUCTS,
            Student.STUDENT);
    }
}
