/*
 * This file is generated by jOOQ.
 */
package com.demo.jooq.jooqdemo.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.address_aid_seq</code>
     */
    public static final Sequence<Integer> ADDRESS_AID_SEQ = new SequenceImpl<Integer>("address_aid_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.human_id_seq</code>
     */
    public static final Sequence<Integer> HUMAN_ID_SEQ = new SequenceImpl<Integer>("human_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.student_id_seq</code>
     */
    public static final Sequence<Integer> STUDENT_ID_SEQ = new SequenceImpl<Integer>("student_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
